server:
    port: 5212

spring:
    application: 
        name: attemper-executor
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        hikari:
            first:
                jdbc-url: jdbc:mysql://127.0.0.1:3306/attemper?allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: fumingren2076
                connection-test-query: select 1  # mysql/sqlserver/postgresql
                # connection-test-query: select 1 from dual  # oracle
                minimum-idle: 5
                maximum-pool-size: 100
                pool-name: first
                max-lifetime: 1800000
            second:
                jdbc-url: jdbc:mysql://127.0.0.1:3306/log?allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: fumingren2076
                connection-test-query: select 1  # mysql/sqlserver/postgresql
                # connection-test-query: select 1 from dual  # oracle
                minimum-idle: 5
                maximum-pool-size: 100
                pool-name: second
                max-lifetime: 1800000
    jackson: 
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        defaultPropertyInclusion: non_null
        deserialization: 
            FAIL_ON_UNKNOWN_PROPERTIES: false

mybatis:
    mapperLocations: classpath*:mapper/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: true
      variables:
        tablePrefix: attemper_

# eureka
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application_instance_id:${random.value}}
    preferIpAddress: true
  client:
    fetchRegistry: true
    region: default
    availabilityZones:
      default: defaultZone
    preferSameZone: false
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.github.attemper: debug

camunda:
  bpm:
    default-number-of-retries: 1
    job-execution:
      lock-time-in-millis: 10800000 # 3h

#app:
#  snow-flake:
#    data-center-id: 0
#    machine-id: 20
